### ISSUE TITLE
I install in python 3 but it run python 2.7

### ISSUE THREAD

**Issue by wannaphong** [awni/cuthon#1]
I using sudo pip3 install cuthon
but 
```
$ cuthon 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by awni** [comment]
cuthon will pick up whichever default version of python you are using. So if the output of `python -V` is 2.7 then cuthon will use 2.7 if the output is 3.X then cuthon will use that version.  One way to switch would be to set the python version in your PATH. Another way to switch is to use a virtaulenv or an anaconda environment which default to python3.
