### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by stakemura** [awni/cuthon#2]
Unfortunately, this original code doesn't work on Python 3.
```python
    least_list = zip(*least_list)[0]
```
Could you modify it like the following code?
```python
    least_list = list(zip(*least_list))[0]
```

**Comment by awni** [comment]
Thanks for pointing this out. Done in commit 39758c882bc16834da774a5776f8f9540eb8192e and updated in pypi

**Comment by stakemura** [comment]
Thanks!
