### ISSUE TITLE
Not enough free GPus found, aborting.

### ISSUE THREAD

**Issue by Prospero1** [awni/cuthon#4]
Hi there, after install ubuntu 18.04 - nvidia, python etc. I'm trying to run python script with cuthon, there's shows up a message that:

Not enough free GPUs found. Aborting. Any solution what I forget to install else to show up cuda devices ?

**Comment by awni** [comment]
I'd guess the problem is it's not detecting that your GPUs are free. You can try passing '-l' as an argument for "least used" or increase this threshold to be 0.1 or maybe even higher.

https://github.com/awni/cuthon/blob/master/cuthon.py#L12
